name: BasedTimber
version: 0.0.1
main: io.papermc.basedtimber.Main
description: The based timber plugin
author: pairnon
website: https://github.com/pairnon/BasedTimber
api-version: '1.20'
commands:
  registerlog:
    description: Register logs for building
    usage: /registerlog