name: BasedTimber
version: 1.0.3
main: io.papermc.basedtimber.Main
description: Tree timber plugin
author: pairnon
website: https://github.com/pairnon/BasedTimber
api-version: '1.20'
commands:
  toggletimber:
    description: Toggle timber mode for felling trees
    usage: toggletimber